# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "fastexcel>=0.20.2",
#     "polars>=1.43.2",
# ]
# ///
import polars as pl
import string
import argparse
from pathlib import Path
import datetime
from dataclasses import dataclass
import sys

SIC_STRING = """

  - NAME: $magnet_name
    FPGA_TYPE: $fpga_type
    FPGA_TYPE_NUMBER: $fpga_type_number
    TERMINAL_PORT: $terminal_port"""

SIC_TEMPLATE = string.Template(SIC_STRING)

AUTOGENERATED_MESSAGE = f"###### AUTOGENERATED FROM MAGNET SPREADSHEET ON {str(datetime.datetime.now())} ######\n\
#### ANYTHING WRITTEN BELOW THIS LINE WILL BE ERASED DURING NEXT GENERATION #####"


"""
The different techincal areas have different spread sheets.
This configuration is to map the column index to a standard column name.
This allows for columns to be standardised and filtered more easily

For example the frc magnet groupings is the same header cell as
PSI Controler card in the booster and cia meaning it will be hard to filter by

Also, some of the same columns have different names e.g.
LINAC: PSI Controller card/SIC,
BR: PSI Controller card/SIC,
CIA: PSI Controller card/SIC/FRC

"""

@dataclass
class ColumnConfig:
    # Number of columns until the data begins
    #   We dont mind removing column names here as they
    #   are renamed by column_names
    header_size: int

    # Index (numeric) of the desired columns
    #   Needs to use index and not column name as the
    #   FOFB groupings share the header with PSI
    #   Controller Type
    relevant_columns: list

    # What to rename the column in the dataframe
    #   same columns must be the same between pages
    column_names: list


def columns_to_index(cols):
    def column_to_index(col):
        num = 0
        for c in col:
            if c in string.ascii_letters:
                num = num * 26 + (ord(c.upper()) - ord("A")) + 1
        return num - 1

    return [column_to_index(col) for col in cols]

"""
NOTE:   I have put placeholders XX and XY as the columns of Terminal Server and
        the terminal port. The order of the column index list needs to correspond
        to the order of the column names.
"""

LINAC_COLUMNS_OF_INTEREST = columns_to_index(["A", "XX", "XY", "AC"])
LINAC_COLUMN_NAMES = [
    "Magnet ID",
    "Terminal Server",
    "Terminal Port",
    "PSI Controller",
]
LINAC_COLUMN_CONFIG = ColumnConfig(
    2, LINAC_COLUMNS_OF_INTEREST, LINAC_COLUMN_NAMES)

BOOSTER_COLUMNS_OF_INTEREST = columns_to_index(["A", "XX", "XY", "BA", "BB", "BD"])
BOOSTER_COLUMN_NAMES = [
    "Magnet ID",
    "Terminal Server",
    "Terminal Port",
    "PSI Controller",
    "FRC Groupings",
    "Is FOFB?",
]
BOOSTER_COLUMN_CONFIG = ColumnConfig(
    2, BOOSTER_COLUMNS_OF_INTEREST, BOOSTER_COLUMN_NAMES
)

CIA_COLUMNS_OF_INTEREST = columns_to_index(["A", "XX", "XY", "AP", "AU", "AV", "AX"])
CIA_COLUMN_NAMES = [
    "Magnet ID",
    "Terminal Server",
    "Terminal Port",
    "PSU Type",
    "PSI Controller",
    "FRC Groupings",
    "Is FOFB?",
]
CIA_COLUMN_CONFIG = ColumnConfig(5, CIA_COLUMNS_OF_INTEREST, CIA_COLUMN_NAMES)


NUM_CIAS = 24
NUM_BOOSTERS = 4
RELEVANT_SHEETS = {
    "LINAC": LINAC_COLUMN_CONFIG,
    **{f"BR{i:02d} CIA": BOOSTER_COLUMN_CONFIG for i in range(1, NUM_BOOSTERS + 1)},
    **{f"CIA {i:02d}": CIA_COLUMN_CONFIG for i in range(1, NUM_CIAS + 1)},
}


# TODO Needs to be updated
def parse_type_number(value):
    return 123


def clean_file(file: Path):
    with file.open("r") as read_file:
        lines = read_file.readlines()
        safe_line = len(lines)
        for i, line in enumerate(lines):
            if line.startswith("iocs:"):
                safe_line = i
                break

            if i == len(lines) - 1:
                raise EOFError("Reached end of file without finding 'iocs:'")

    with file.open("w") as write_file:
        write_file.writelines(lines[: safe_line + 1])
        write_file.write(AUTOGENERATED_MESSAGE)


def append_sic_devices(file, magnets: pl.DataFrame):
    sic_magnets = magnets.filter(pl.col("PSI Controller") == "SIC")
    if len(sic_magnets) == 0:
        return
    for sic_data in sic_magnets.iter_rows(named=True):
        file.write(
            SIC_TEMPLATE.substitute(
                magnet_name=sic_data["Magnet ID"].lower(),
                fpga_type="SIC_DPS",
                fpga_type_number=parse_type_number(sic_data.get("PSU Type", 123)),
                terminal_port=sic_data["Terminal Port"]
            )
        )


def append_frc_magnets(file, magnets: pl.DataFrame):
    frc_magnets = magnets.filter(pl.col("PSI Controller") == "FRC")
    if len(frc_magnets) == 0:
        return
    frc_group = frc_magnets.group_by(
        pl.col("FRC Groupings").round(0), maintain_order=True
    )

    magnet_list = ["MAGNET_ONE", "MAGNET_TWO", "MAGNET_THREE", "MAGNET_FOUR"]
    for frc_index, frc_rows in frc_group:

        # We continuesly append to this string to add the magnet names
        magnet_string = ""
        terminal_ports = set()
        frc_types = set()
        for magnet_index, frc_data in enumerate(frc_rows.iter_rows(named=True)):
            magnet_id = frc_data["Magnet ID"]
            if magnet_index == 0:
                frc_name = magnet_id
            magnet_string += f"{magnet_list[magnet_index]}: {magnet_id}\n"
            frc_type = "FOFB" if frc_data["Is FOFB?"] else "SOFB"
            frc_types.add(frc_type)
            terminal_ports.add(frc_data["Terminal Port"])

        assert len(frc_types) == 1, "All FRC Magnets must be the same type"
        assert len(terminal_ports) == 1, "All FRC magnets must have the same terminal Port"
        file.write(f"\n# FRC: {int(frc_index[0])}")
        file.write(
            SIC_TEMPLATE.substitute(
                magnet_name=frc_name.lower(),
                fpga_type=frc_type,
                fpga_type_number=123,
                terminal_port=terminal_ports.pop(),
            ) + magnet_string
        )


if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        description="Writes the group ioc instances for the d2dcc iocs from "
        "the magnet spreadsheet.",
    )
    ap.add_argument("input-spreadsheet", type=str)
    args = vars(ap.parse_args(sys.argv[1:]))

    spreadsheet = pl.read_excel(args["input-spreadsheet"],
                                          sheet_id=0,
                                          has_header=True,
                                          drop_empty_cols=False,
                                          drop_empty_rows=False)
    top = Path(__file__).parents[0]
    services_dir = Path(top / "services")

    for page, column_config in RELEVANT_SHEETS.items():
        df = (
            spreadsheet[page]
            .slice(column_config.header_size)
            .select(pl.nth(column_config.relevant_columns))
        )
        # filter out magnets by if they have a terminal server address and port
        df.columns = column_config.column_names
        magnet_sive = [
            pl.col("Terminal Server").is_not_null(),
            pl.col("Terminal Port").is_not_null(),
        ]
        cleaned_df = df.filter(magnet_sive)
        if len(cleaned_df) == 0:
            print(f"{page}: No magnets with Terminal server and port")
            continue

        ts_groups = df.group_by(pl.col("Terminal Server"))
        for ts, magnet_controllers in ts_groups:
            terminal_server = ts[0]
            if terminal_server is None:
                continue

            directory = services_dir / str(terminal_server).lower()

            values_file = directory / "values.yaml"
            if not values_file.exists():
                print(f"Missing value.yaml file at {values_file}")
                continue

            clean_file(values_file)
            with values_file.open("+a") as file:
                append_sic_devices(file, magnet_controllers)
                append_frc_magnets(file, magnet_controllers)
