import polars as pl
from string import Template
import argparse
from pathlib import Path
import datetime
import sys

SIC_STRING = """

  - NAME: $magnet_name
    FPGA_TYPE: $fpga_type
    FPGA_TYPE_NUMBER: $fpga_type_number"""

FRC_STRING = SIC_STRING + """
    MAGNET_ONE: $magnet_one
    MAGNET_TWO: $magnet_two
    MAGNET_THREE: $magnet_three
    MAGNET_FOUR: $magnet_four
    """

SIC_TEMPLATE = Template(SIC_STRING)
FRC_TEMPLATE = Template(FRC_STRING)

PSU_CONTROLER_TABLE = {
    "OCEM 200A MODULE": "SIC_DPS",
    "DLS 200A MODULE": "SIC_DPS",
    "SC (SIC controller) ": "SIC_DPS",
    "FOFB SC": "SOFB",
    "SC (PSI controller) ": "SIC_DPS",
    "FOFB FC": "FOFB",
    "DLS 50A MODULE": "SIC_DPS",
}

AUTOGENERATED_MESSAGE = (
    f"###### AUTOGENERATED FROM MAGNET SPREADSHEET ON {str(datetime.datetime.now())} ######")

def parse_type_number(value):
    return 123

def clean_file(values_file):
    with values_file.open("r") as read_file:
        lines = read_file.readlines()
        safe_line = len(lines)
        for i, line in enumerate(lines):
            if line.startswith("iocs:"):
                safe_line = i
                break

            if i == len(lines) - 1:
                raise EOFError("Reached end of file without finding 'iocs:'")

    with values_file.open("w") as write_file:
        write_file.writelines(lines[:safe_line+1])
        write_file.write(AUTOGENERATED_MESSAGE)

def open_spreadsheet(spreadsheet_file, cia_tag):
    df = pl.read_excel(
        spreadsheet_file,
        sheet_name=cia_tag,
        engine="xlsx2csv",
        engine_options={"skip_empty_lines": True},
        schema_overrides={"Current rating (A)": pl.Utf8},
        read_options={
            "has_header": True,
            "skip_rows": 2,
            "columns": [
                0,      # Magnet ID
                41,     # PSU Type
                47,     # FRC magnet number
            ],
            "new_columns": [
                "Magnet ID",
                "PSU Type",
                "FRC Magnet Number",
            ],
        },
    )

    magnet_sive = pl.any_horizontal(pl.col("Magnet ID").str.starts_with("SR"))
    magnet_controlers = df.filter(magnet_sive)
    magnet_controlers = magnet_controlers.filter(
        pl.any_horizontal(pl.col("PSU Type").is_not_null())
    )

    return magnet_controlers


def append_sic_devices(file, magnets):
    sic_magnets = magnets.filter(
        pl.col("PSU Type").is_in(
            [key for key, value in PSU_CONTROLER_TABLE.items() if value == "SIC_DPS"]
        )
    )

    for data in sic_magnets.iter_rows(named=True):
        file.write(
            SIC_TEMPLATE.substitute(
                magnet_name=data["Magnet ID"],
                fpga_type=PSU_CONTROLER_TABLE[data["PSU Type"]],
                fpga_type_number=parse_type_number(data["PSU Type"]),
            )
        )


def append_frc_magnets(file, magnets):

    frc_controllers = magnets.filter(
        pl.col("PSU Type").is_in(
            [
                key
                for key, value in PSU_CONTROLER_TABLE.items()
                if (value == "FOFB" or value == "SOFB")
            ]
        )
    )

    frc_group = frc_controllers.group_by(
        pl.col("FRC Magnet Number").round(0), maintain_order=True
    )

    magnet_list = ["magnet_one", "magnet_two", "magnet_three", "magnet_four"]
    for _, data in frc_group:
        magnet_names = {}
        frc_type = set()
        for magnet_index, magnet_controller in enumerate(data.iter_rows(named=True)):
            magnet_names[magnet_list[magnet_index]] = magnet_controller["Magnet ID"]
            frc_type.add(PSU_CONTROLER_TABLE[magnet_controller["PSU Type"]])

        assert len(set(magnet_names.values())) == len(
            data
        ), "All FRC Magnet names must be unique"

        assert len(frc_type) == 1, "All FRC magnet types must be the same"
        file.write(
            FRC_TEMPLATE.substitute(
                magnet_name=magnet_names["magnet_one"],
                fpga_type=frc_type.pop(),
                fpga_type_number=123,
                **magnet_names,
            )
        )


if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        description="Writes the group ioc instances for the d2dcc iocs from "
        "the magnet spreadsheet.",
        epilog="Hello World",
    )
    ap.add_argument("input-spreadsheet", type=str)

    spreadsheet_filepath = "/scratch/ygn40972/repos/tutorials/t01-services/Magnet to Epics end-to-end connections V04.xlsx"
    args = vars(ap.parse_args(sys.argv[1:]))

    top = Path(__file__).parents[0]
    services_dir = Path(top / "services")
    cia_directories = [
        x for x in services_dir.iterdir() if (x.is_dir() and "CIA-" in x.name)
    ]
    for cia_dir in cia_directories:
        values_file = cia_dir / "values.yaml"
        cia_tag = cia_dir.name.replace("-", " ")
        assert values_file.exists(), f"Missing value.yaml file at {values_file}"

        magnet_controllers = open_spreadsheet(args["input-spreadsheet"], cia_tag)

        clean_file(values_file)
        with values_file.open("+a") as file:
            append_sic_devices(file, magnet_controllers)
            append_frc_magnets(file, magnet_controllers)
