# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "fastexcel>=0.20.2",
#     "polars>=1.43.2",
# ]
# ///
import polars as pl
import string
import argparse
from pathlib import Path
import datetime
from dataclasses import dataclass
import sys

# Tested on 18th August,

SIC_STRING = """

  - NAME: $magnet_name
    FPGA_TYPE: $fpga_type
    FPGA_TYPE_NUMBER: $fpga_type_number"""

FRC_STRING = SIC_STRING + """
    MAGNET_ONE: $magnet_one
    MAGNET_TWO: $magnet_two
    MAGNET_THREE: $magnet_three
    MAGNET_FOUR: $magnet_four
    """

SIC_TEMPLATE = string.Template(SIC_STRING)
FRC_TEMPLATE = string.Template(FRC_STRING)

AUTOGENERATED_MESSAGE = f"###### AUTOGENERATED FROM MAGNET SPREADSHEET ON {str(datetime.datetime.now())} ######\n\
#### ANYTHING WRITTEN BELOW THIS LINE WILL BE ERASED DURING NEXT GENERATION #####"




# The different techincal areas have different spread sheets.
# This configuration is to map the column index to a standard column name.
# This allows for columns to be standardised and filtered more easily
# For example the frc magnet groupings is the same header cell as
# PSI Controler card in the booster and cia meaning it will be hard to filter by
# Also, some of the same columns have different names e.g.
# LINAC: PSI Controller card/SIC,
# BR: PSI Controller card/SIC,
# CIA: PSI Controller card/SIC/FRC

@dataclass
class ColumnConfig:
    header_size: int        # Number of columns until the data begins
                            # ( We dont mind removing column names here as they
                            # are renamed here )

    relevant_columns: list  # Index (numeric) of the desired columns
                            # ( Needs to use index and not column name as the
                            #   FOFB groupings share the header with PSI
                            #   Controller Type )

    column_names: list      # What to rename the columns


def col2num(col):
    num = 0
    for c in col:
        if c in string.ascii_letters:
            num = num * 26 + (ord(c.upper()) - ord('A')) + 1
    return num - 1

LINAC_COLUMNS_OF_INTEREST = list(map(col2num, ["A", "B", "C", "AC"]))
LINAC_COLUMN_NAMES = [
    "Magnet ID",
    "Terminal Server",
    "Terminal Port",
    "PSI Controller"]
LINAC_COLUMN_CONFIG = ColumnConfig(2, LINAC_COLUMNS_OF_INTEREST, LINAC_COLUMN_NAMES)

# Magnet ID, PSI Controller card, FRC Magnet groupings, Part of FOFB
BOOSTER_COLUMNS_OF_INTEREST = list(map(
    col2num, ["A", "B", "C", "BA", "BB", "BD"]))
BOOSTER_COLUMN_NAMES = [
    "Magnet ID",
    "Terminal Server",
    "Terminal Port",
    "PSI Controller",
    "FRC Groupings",
    "Is FOFB?"]
BOOSTER_COLUMN_CONFIG = ColumnConfig(
    3,
    BOOSTER_COLUMNS_OF_INTEREST,
    BOOSTER_COLUMN_NAMES)

# Magnet ID, PSU Type, PSI Controller card, FRC Magnet groupings, Part of FOFB
CIA_COLUMNS_OF_INTEREST = list(map(col2num,
                                   ["A", "B", "C", "AP", "AU", "AV", "AX"]))
CIA_COLUMN_NAMES = [
    "Magnet ID",
    "Terminal Server",
    "Terminal Port",
    "PSU Type",
    "PSI Controller",
    "FRC Groupings",
    "Is FOFB?"]
CIA_COLUMN_CONFIG = ColumnConfig(6, CIA_COLUMNS_OF_INTEREST, CIA_COLUMN_NAMES)


NUM_CIAS = 24
NUM_BOOSTERS = 4
RELEVANT_SHEETS = {
    "LINAC": LINAC_COLUMN_CONFIG,
    **{f"BR{i:02d} CIA": BOOSTER_COLUMN_CONFIG for i in range(1, NUM_BOOSTERS+1)},
    **{f"CIA {i:02d}": CIA_COLUMN_CONFIG for i in range(1, NUM_CIAS+1)},
    }


def parse_type_number(value):
    return 123


def clean_file(file: Path):
    with file.open("r") as read_file:
        lines = read_file.readlines()
        safe_line = len(lines)
        for i, line in enumerate(lines):
            if line.startswith("iocs:"):
                safe_line = i
                break

            if i == len(lines) - 1:
                raise EOFError("Reached end of file without finding 'iocs:'")

    with file.open("w") as write_file:
        write_file.writelines(lines[: safe_line + 1])
        write_file.write(AUTOGENERATED_MESSAGE)


def append_sic_devices(file, magnets: pl.DataFrame):
    sic_magnets = magnets.filter(pl.col("PSI Controller") == "SIC")
    for sic_data in sic_magnets.iter_rows(named=True):
        file.write(
            SIC_TEMPLATE.substitute(
                magnet_name=sic_data["Magnet ID"],
                fpga_type="SIC_DPS",
                fpga_type_number=parse_type_number(sic_data.get("PSU Type", 123)),
            )
        )


def append_frc_magnets(file, magnets: pl.DataFrame):
    frc_magnets = magnets.filter(pl.col("PSI Controller") == "FRC")
    frc_group = frc_magnets.group_by(
        pl.col("FRC Groupings").round(0), maintain_order=True
    )

    magnet_list = ["magnet_one", "magnet_two", "magnet_three", "magnet_four"]
    for frc_index, frc_rows in frc_group:

        magnet_names = {}
        for magnet_index, frc_data in enumerate(frc_rows.iter_rows(named=True)):
            magnet_names[magnet_list[magnet_index]] = frc_data["Magnet ID"]
            frc_type = "FOFB" if frc_data["Is FOFB?"] else "SOFB"

        file.write(f"\n# FRC: {int(frc_index[0])}")
        file.write(
            FRC_TEMPLATE.safe_substitute(
                magnet_name=magnet_names["magnet_one"],
                fpga_type=frc_type,
                fpga_type_number=123,
                **magnet_names,
            )
        )


if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        description="Writes the group ioc instances for the d2dcc iocs from "
        "the magnet spreadsheet.",
    )
    ap.add_argument("input-spreadsheet", type=str)

    args = vars(ap.parse_args(sys.argv[1:]))

    spreadsheet = pl.read_excel(
                args["input-spreadsheet"],
                sheet_id=0,
                has_header=False)
    top = Path(__file__).parents[0]
    services_dir = Path(top / "services")

    # Don't clean directories which have been seen
    directories_seen = set()

    for page, column_config in RELEVANT_SHEETS.items():
        df = (spreadsheet[page]
                .slice(column_config.header_size)
                .select(pl.nth(column_config.relevant_columns)))
        # filter out magnets by if they have a terminal server address and port
        df.columns = column_config.column_names
        magnet_sive = [
            pl.col("Terminal Server").is_not_null(),
            pl.col("Terminal Port").is_not_null(),
            ]
        cleaned_df = df.filter(magnet_sive)
        if len(cleaned_df) == 0:
            print(f"{page}: No magnets with Terminal server and port")
            continue

        ts_groups = df.group_by(pl.col("Terminal Server"))
        for ts, magnet_controllers in ts_groups:
            terminal_server = ts[0]
            if terminal_server is None or (
                directory := services_dir / terminal_server) in directories_seen:
                continue

            values_file = directory / "values.yaml"
            if not values_file.exists():
                print(f"Missing value.yaml file at {values_file}")
                continue

            clean_file(values_file)
            directories_seen.add(directory)
            with values_file.open("+a") as file:
                append_sic_devices(file, magnet_controllers)
                append_frc_magnets(file, magnet_controllers)
