#!/usr/bin/expect -f

set timeout 60

set d2dcc_dir $env(D2DCC_DIR)

set telnet_server $env(TELNET_SERVER)
set telnet_port $env(TELNET_PORT)
set hostname $env(NAME)

set fpga_bin_dir $env(FPGA_BIN_DIR)
set fpga_type $env(FPGA_TYPE)
set fpga_type_number $env(FPGA_TYPE_NUMBER)

set installer_dir "/tmp"

set host_network "dev"

# Configure hostname on the colibri
spawn telnet $server $port
expect {
    "Connected to $server" {
        send "\n\r"
        expect -re {.*#\s*}
    }
    "Connection closed by foreign host." {
        puts stdout "\nError: $server:$port refused the connection"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        puts stdout "\nError: Timed out trying to connect to $server:$port."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to connect to $server:$port."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
}
send "configure-network -w -r $host_network $hostname\r"
expect {
    "Starting local mounts: " {
        expect -re {.*#\s*}
        puts stdout "\nHostname configured to: $hostname"
    }
    "Hostname '$hostname' not known for network $host_network" {
        puts stdout "\nError: Bad hostname"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        puts stdout "\nError: Timed out configuring the network."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to configure the network."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
}

close

# Copy installer files to colibri via SCP
spawn scp \
    "-O" \
    "$d2dcc_dir/bin/linux-arm_elhf/installer_server.sh" \
    "$fpga_bin_dir/$fpga_type.bin" \
    "root@$hostname:$installer_dir"

# SHA Fingerprint Promt
expect "yes/no" {
        send "yes\r"
}

expect "password" {
    send "root\r"
    expect eof
    puts stdout "\nFiles transfered to colibri"
}

# Run the server installer script
spawn telnet $server $port
expect {
    "Connected to $server" {
        send "\n\r"
        expect -re {.*#\s*}
    }
    "Connection closed by foreign host." {
        puts stdout "\nError: $server:$port refused the connection"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        puts stdout "\nError: Timed out trying to connect to $server:$port."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to connect to $server:$port."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
}
send  "echo \"export K8S_FPGA_TYPE=$fpga_type; export K8S_FPGA_TYPE_NUMBER=$fpga_type_number \" > /opt/server_env\r"
expect {
    -re {.*#\s*} {
        puts stdout "\nenv file written to /opt/server_env"
    }
    timeout {
        puts stdout "\nError: Timed out writing env file"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to write to env file"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
}

send "cd $installer_dir\r"
send "./installer_server.sh -i\r"
expect {
    "ok." {
        puts stdout "\nServer has been installed."
        set exit_code 0
    }
    "ERROR" {
        puts stdout "\nError: Failed installing server.\r $expect_out"
        set exit_code 1
    }
    timeout {
        puts stdout "\nError: Timed out installing the server"
        set exit_code 1
    }
}

puts stdout "\nClosing Telnet Connection"
close
wait
exit $exit_code
