#!/usr/bin/expect -f

set timeout 60

set d2dcc_dir $env(D2DCC_DIR)

set telnet_server $env(TELNET_SERVER)
set telnet_port $env(TELNET_PORT)
set hostname $env(NAME)

set fpga_bin_dir $env(FPGA_BIN_DIR)
set fpga_type $env(FPGA_TYPE)
set fpga_type_number $env(FPGA_TYPE_NUMBER)

set installer_dir "/tmp"

set host_network "dev"
proc begin_telnet_connection {server port} {
    spawn telnet $server $port
    expect {
        "Connected to $server" {
            send "\n\r"
            expect "# "
            return $spawn_id }
        "Connection closed by foreign host." {
            puts "Error: $server:$port refused the connection"
        }
        timeout {
            puts "Error: Timed out trying to connect to $server:$port."
        }
        eof {
            puts "Error: Failed to connect to $server:$port."
        }
    }
    close
    wait
    exit 1
}

# Configure hostname on the colibri
set telnet_id [begin_telnet_connection $telnet_server $telnet_port]
send -i $telnet_id "configure-network -w -r $host_network $hostname\r"
expect -i $telnet_id {
    "Starting local mounts: " {
        expect "ok."
        expect "# "
        puts "Hostname configured to: $hostname"
    }
    "Hostname '$hostname' not known for network $host_network" {
        puts "Error: Bad hostname"
        puts "Closing Telnet Connection"
        close -i $telnet_id
        exit 1
    }
    timeout {
        puts "Error: Timed out configuring the network."
        puts "Closing Telnet Connection"
        close -i $telnet_id
        exit 1
    }
    eof {
        puts "Error: Failed to configure the network."
        puts "Closing Telnet Connection"
        close -i $telnet_id
        exit 1
    }
}

puts "Closing Telnet Connection"
close -i $telnet_id
puts "\r"

# Copy installer files to colibri via SCP
spawn scp -O \
    "$d2dcc_dir/bin/linux-arm_elhf/installer_server.sh" \
    "$fpga_bin_dir/$fpga_type.bin" \
    "root@$hostname:$installer_dir"

# SHA Fingerprint Promt
expect "yes/no" {
        send "yes\r"
}

expect "password" {
    send "root\r"
    expect eof
    puts "Files transfered to colibri"
}

# Run the server installer script
set telnet_id [begin_telnet_connection $telnet_server $telnet_port]
send -i $telnet_id "echo \"export K8S_FPGA_TYPE=$fpga_type; export K8S_FPGA_TYPE_NUMBER=$fpga_type_number \" > /opt/server_env\r"
expect -i $telnet_id {
    "# " {
        puts "env file written to \/opt\/server_env"
    }
    timeout {
        puts "ERROR: Timed out writing env file"
        puts "Closing Telnet Connection"
        close -i $telnet_id
        exit 1
    }
    eof {
        puts "ERROR: Failed to write to env file"
        puts "Closing Telnet Connection"
        close -i $telnet_id
        exit 1
    }
}
send -i $telnet_id "cd $installer_dir\r"
send -i $telnet_id "./installer_server.sh -i\r"
expect -i $telnet_id {
    "ok." {
        puts "Server has been installed."
    }
    timeout {
        puts "ERROR: timed out installing the server"
        puts "Closing Telnet Connection"
        close -i $telnet_id
        exit 1
    }
}
close -i $telnet_id
exit 0
