#!/usr/bin/expect -f

set timeout 60

set d2dcc_dir $env(D2DCC_DIR)

set telnet_server $env(TELNET_SERVER)
set telnet_port $env(TELNET_PORT)
set hostname $env(NAME)

set fpga_bin_dir $env(FPGA_BIN_DIR)
set fpga_type $env(FPGA_TYPE)
set fpga_type_number $env(FPGA_TYPE_NUMBER)

set installer_dir "/tmp"

set host_network "dev"

set prompt "-re {.*#\s*}"

proc close_telnet {process_id} {
    puts stdout "\nClosing Telnet Connection"
    close -i $process_id
    wait -i $process_id
}

proc begin_telnet_connection {server port} {
    spawn telnet $server $port
    expect {
        "Connected to $server" {
            send "\n\r"
            expect "$prompt"
            return $spawn_id }
        "Connection closed by foreign host." {
            puts stdout "\nError: $server:$port refused the connection"
        }
        timeout {
            puts stdout "\nError: Timed out trying to connect to $server:$port."
        }
        eof {
            puts stdout "\nError: Failed to connect to $server:$port."
        }
    }
    exit 1
}

# Configure hostname on the colibri
set telnet_id [begin_telnet_connection $telnet_server $telnet_port]
send -i $telnet_id "configure-network -w -r $host_network $hostname\r"
expect -i $telnet_id {
    "Starting local mounts: " {
        expect $prompt
        puts stdout "\nHostname configured to: $hostname"
    }
    "Hostname '$hostname' not known for network $host_network" {
        puts stdout "\nError: Bad hostname"
        close_telnet $telnet_id
        exit 1
    }
    timeout {
        puts stdout "\nError: Timed out configuring the network."
        close_telnet $telnet_id
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to configure the network."
        close_telnet $telnet_id
        exit 1
    }
}

close_telnet $telnet_id

# Copy installer files to colibri via SCP
spawn scp \
    "-O" \
    "$d2dcc_dir/bin/linux-arm_elhf/installer_server.sh" \
    "$fpga_bin_dir/$fpga_type.bin" \
    "root@$hostname:$installer_dir"

# SHA Fingerprint Promt
expect "yes/no" {
        send "yes\r"
}

expect "password" {
    send "root\r"
    expect eof
    puts stdout "\nFiles transfered to colibri"
}

# Run the server installer script
set telnet_id [begin_telnet_connection $telnet_server $telnet_port]
send -i $telnet_id "echo \"export K8S_FPGA_TYPE=$fpga_type; export K8S_FPGA_TYPE_NUMBER=$fpga_type_number \" > /opt/server_env\r"
expect -i $telnet_id {
    $prompt {
        puts stdout "\nenv file written to \/opt\/server_env"
    }
    timeout {
        puts stdout "\nError: Timed out writing env file"
        close_telnet $telnet_id
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to write to env file"
        close_telnet $telnet_id
        exit 1
    }
}

send -i $telnet_id "cd $installer_dir\r"
send -i $telnet_id "./installer_server.sh -i\r"
expect -i $telnet_id {
    "ok." {
        puts stdout "\nServer has been installed."
    }
    "ERROR" {
        puts stdout "\nError: Failed installing server.\r $expect_out"
        close_telnet $telnet_id
        exit 1
    }
    timeout {
        puts stdout "\nError: Timed out installing the server"
        close_telnet $telnet_id
        exit 1
    }
}

close_telnet $telnet_id
exit 0
