#!/usr/bin/expect -f

set timeout 30

set telnet_server $env(TELNET_SERVER)
set telnet_port $env(TELNET_PORT)

set hostname $env(NAME)

set host_network "dev"

proc log_message {message} {
    puts stdout "\n$message"
}

log_message "\n***** Configure hostname on colibri *****"
spawn telnet $telnet_server $telnet_port
expect {
    "Connected to $telnet_server" {
        send "\n\r"
        expect -re {.*#\s*}
    }
    "Connection closed by foreign host." {
        log_message "Error: $telnet_server:$telnet_port refused the connection"
        exit 1
    }
    timeout {
        log_message "Error: Timed out trying to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        log_message "Error: Failed to connect to $telnet_server:$telnet_port."
        exit 1
    }
}

send "configure-network -w -r $host_network $hostname && echo SUCCESS || echo FAILURE\r"
expect {
    "SUCCESS" {
        expect -re {.*#\s*}
        log_message "Hostname configured to: $hostname"
        log_message "Closing Telnet Connection"
    }
    "FAILURE" {
        log_message "ERROR: Failed to configure hostname $expect_out(buffer)"
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        log_message "ERROR: Timed out configuring the network."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
}

# Delete any old ssh keys
send "rm -f /root/.ssh/authorized_keys"
close
wait

log_message "\n***** Transfer SSH Authorisationkey to colibri"
# Need to transfer the FPGA binary
set home_dir $env(HOME)
spawn ssh-copy-id -i ${home_dir}/.ssh/id_${hostname} root@$hostname
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password" {
        send "root\r"
        exp_continue
    }
    "Number of key(s) added: 1" {
        log_message "SSH authorization key transferred to colibri"
    }
}
