#!/usr/bin/expect -f

set timeout 30

set d2dcc_dir $env(D2DCC_DIR)

set telnet_server $env(TELNET_SERVER)
set telnet_port $env(TELNET_PORT)

set hostname $env(NAME)

set fpga_bin_dir $env(FPGA_BIN_DIR)
set fpga_type $env(FPGA_TYPE)
set fpga_type_number $env(FPGA_TYPE_NUMBER)

set installer_dir "/tmp"

set host_network "dev"

proc log_message {message} {
    puts stdout "\n$message"
}

log_message "\n***** Configure hostname on colibri *****"
spawn telnet $telnet_server $telnet_port
expect {
    "Connected to $telnet_server" {
        send "\n\r"
        expect -re {.*#\s*}
    }
    "Connection closed by foreign host." {
        log_message "Error: $telnet_server:$telnet_port refused the connection"
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        log_message "Error: Timed out trying to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        log_message "Error: Failed to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
}

send "configure-network -w -r $host_network $hostname && echo SUCCESS || echo FAILURE\r"
expect {
    "SUCCESS" {
        expect -re {.*#\s*}
        log_message "Hostname configured to: $hostname"
        log_message "Closing Telnet Connection"
        close
        wait
    }
    "FAILURE" {
        log_message "ERROR: Failed to configure hostname $expect_out(buffer)"
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        log_message "ERROR: Timed out configuring the network."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
}

log_message "\n***** Transfer install files to Colibri via SCP"
# Need to transfer the FPGA binary
spawn scp \
    "-O" \
    "$d2dcc_dir/bin/linux-arm_elhf/installer_server.sh" \
    "root@$hostname:$installer_dir"

# SHA Fingerprint Promt
expect "yes/no" {
    send "yes\r"
}

expect "password" {
    send "root\r"
    expect eof
    log_message "Files transfered to colibri"
}


log_message "\n***** Set up environment and install the server *****"
spawn ssh root@$hostname "
    echo \"export K8S_FPGA_TYPE=$fpga_type
    export K8S_FPGA_TYPE_NUMBER=$fpga_type_number\" > /opt/server_env"
expect "password" {
    send "root\r"
}

spawn ssh root@$hostname "source /opt/server_env; cd $installer_dir; ./installer_server.sh -i && echo SUCCESS || echo FAILURE"
expect {
    "password" {
        send "root\r"
        exp_continue
    }
    "SUCCESS" {
        log_message "Server has been installed."
        set exit_code 0
    }
    "FAILURE" {
        log_message "Error: Failed installing server. $expect_out(buffer)"
        set exit_code 1
    }
    timeout {
        log_message "Error: Timed out installing the server"
        set exit_code 1
    }
}

exit $exit_code
