#!/usr/bin/expect -f

set timeout 30

set d2dcc_dir $env(D2DCC_DIR)

set telnet_server $env(TELNET_SERVER)
set telnet_port $env(TELNET_PORT)
set hostname $env(SERVER_HOSTNAME)

set fpga_bin_dir $env(FPGA_BIN_DIR)
set fpga_type $env(FPGA_TYPE)
set fpga_type_number $env(FPGA_TYPE_NUMBER)
set server_port $env(SERVER_PORT)
set proc_port $env(SERVER_PROC_PORT)

set installer_dir "/tmp"

set host_network "dev"

proc log_message {message} {
    puts stdout "\n$message"
}

log_message "\n***** Configure hostname on colibri *****"
spawn telnet $telnet_server $telnet_port
expect {
    "Connected to $telnet_server" {
        send "\n\r"
        expect -re {.*#\s*}
    }
    "Connection closed by foreign host." {
        log_message "Error: $telnet_server:$telnet_port refused the connection"
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        log_message "Error: Timed out trying to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        log_message "Error: Failed to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
}
send "configure-network -w -r $host_network $hostname\r"
expect {
    "Starting local mounts: " {
        expect -re {.*#\s*}
        log_message "Hostname configured to: $hostname"
    }
    "Hostname '$hostname' not known for network $host_network" {
        puts stdout "\nError: Bad hostname"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        puts stdout "\nError: Timed out configuring the network."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to configure the network."
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
}

log_message "Closing Telnet Connection"
close
wait



log_message "\n***** Transfer install files to Colibri via SCP"
spawn scp \
    "-O" \
    "$d2dcc_dir/bin/linux-arm_elhf/installer_server.sh" \
    "$fpga_bin_dir/$fpga_type.bin" \
    "root@$hostname:$installer_dir"

# SHA Fingerprint Promt
expect "yes/no" {
    send "yes\r"
}

expect "password" {
    send "root\r"
    expect eof
    log_message "Files transfered to colibri"
}



log_message "\n***** Set up environment and install the server *****"
spawn telnet $telnet_server $telnet_port
expect {
    "Connected to $telnet_server" {
        send "\n\r"
        expect -re {.*#\s*}
    }
    "Connection closed by foreign host." {
        log_message "Error: $telnet_server:$telnet_port refused the connection"
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    timeout {
        log_message "Error: Timed out trying to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        log_message "Error: Failed to connect to $telnet_server:$telnet_port."
        log_message "Closing Telnet Connection"
        close
        wait
        exit 1
    }
}
send  "
    echo \"export K8S_FPGA_TYPE=$fpga_type
    export K8S_FPGA_TYPE_NUMBER=$fpga_type_number
    export SERVER_PORT=$server_port
    export PROC_PORT=$proc_port \" > /opt/server_env\r"

expect {
    -re {.*#\s*} {
        puts stdout "\nenv file written to /opt/server_env"
    }
    timeout {
        puts stdout "\nError: Timed out writing env file"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
    eof {
        puts stdout "\nError: Failed to write to env file"
        puts stdout "\nClosing Telnet Connection"
        close
        wait
        exit 1
    }
}

# Need to move the fpga binary to /opt/bin/@fpga_bin_name@ before installing
# Not done currently as the persistance volume/ mount is not setup for the binaries
send "cd $installer_dir\r"
send "./installer_server.sh -i\r"
expect {
    "ok." {
        log_message "Server has been installed."
        set exit_code 0
    }
    "ERROR" {
        log_message "Error: Failed installing server.\r $expect_out"
        set exit_code 1
    }
    timeout {
        log_message "Error: Timed out installing the server"
        set exit_code 1
    }
}

log_message "Closing Telnet Connection"
close
wait
exit $exit_code
